# Generated by Django 3.2.9 on 2022-02-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220227_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_f',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=100, verbose_name='Пол пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail_agreement',
            field=models.BooleanField(default=False, verbose_name='Соглашение на уведомления'),
        ),
    ]
