# Generated by Django 3.2.9 on 2022-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_f',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол пользователя'),
        ),
    ]
