# Generated by Django 3.2.9 on 2022-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_gender_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender_f',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6, verbose_name='Пол пользователя'),
        ),
    ]
