# Generated by Django 3.2 on 2022-03-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='avtor',
        ),
    ]
