# Generated by Django 3.2 on 2022-03-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='mes_subject',
            new_name='title',
        ),
    ]
