# Generated by Django 3.2 on 2022-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_mes_subject_messages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тема'),
        ),
    ]
